#!/bin/bash

set -e

cd "$(dirname "$0")"

if test $# -ne 1
then
  echo "usage: $0 <node-version>" 1>&2
  exit 1
fi

# Tarball we want
PACKAGE="v${1}.tar.gz"

# Do a conditional get if we don't have the tarball handy
if [ ! -f ${PACKAGE} ]; then
    wget "https://github.com/nodejs/node/archive/${PACKAGE}"
fi

tar -xzvf ${PACKAGE}

echo "$1"

./patch-${1} "$1"
